apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: maestro
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: maestro
    app.kubernetes.io/part-of: maestro
  name: maestro7nif
spec:
  port:
    targetPort: 8000
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: maestro
    weight: 100
status: {}
