apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: maestro
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: maestro
    app.kubernetes.io/part-of: maestro
  name: maestro
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: maestro
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: maestro
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/maestro-rhtap-tenant/maestro/maestro@sha256:eef180b6ab63b21a5910d01e787904f4535db35986cefff8077a1de53f91cbed
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
