apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: maestro
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: maestro
    app.kubernetes.io/part-of: maestro
  name: maestro
spec:
  ports:
  - port: 8000
    targetPort: 8000
  selector:
    app.kubernetes.io/instance: maestro
status:
  loadBalancer: {}
